language: rust

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5

env:
  - LLVM_VERSION=3.5
  - LLVM_VERSION=3.8
rust:
  - stable
  - nightly
os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: linux
      env: LLVM_VERSION=3.5
      rust: stable
      script: cargo build --features static --verbose
    - os: linux
      env: LLVM_VERSION=3.5
      rust: nightly
      script: cargo build --features clippy --verbose
    - os: osx
      rust: stable
      env: LLVM_VERSION=devtools

notifications:
  webhooks: http://build.servo.org:54856/travis

before_install: . ./scripts/travis-before-install.sh
