language: rust

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5

env:
  - LLVM_VERSION=3.5
  - LLVM_VERSION=3.8
rust:
  - stable
  - nightly
os:
  - osx
  - linux

matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: linux
      env: LLVM_VERSION=3.5
      rust: stable
      script: cargo build --features static --verbose
    - os: osx
      env: LLVM_VERSION=devtools
      rust: stable
    - os: linux
      env: LLVM_VERSION=3.5
      rust: nightly
      script: cargo build --features clippy

notifications:
  webhooks: http://build.servo.org:54856/travis

cache: cargo

before_install:
  -
    set -e;
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      if [ "${LLVM_VERSION}" != "devtools" ]; then
        brew update >/dev/null;
        brew install llvm3${LLVM_VERSION#3.};
        export LIBCLANG_PATH=`brew --prefix llvm3${LLVM_VERSION#3.}`/lib/llvm-${LLVM_VERSION}/lib;
      else
        export LIBCLANG_PATH=/Library/Developer/CommandLineTools/usr/lib;
      fi
    else
      export LLVM=clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04;
      wget http://llvm.org/releases/${LLVM_VERSION}/${LLVM}.tar.xz ;
      mkdir llvm;
      tar -xf ${LLVM}.tar.xz -C llvm --strip-components=1;
      export LIBCLANG_PATH=`pwd`/llvm/lib;
    fi
    echo $LIBCLANG_PATH;

after_success: |
  [ "${TRAVIS_RUST_VERSION}" = "stable" ] &&
  [ "${TRAVIS_OS_NAME}" = "linux" ] &&
  [ "${LLVM_VERSION}" = "3.8" ] &&
  ./scripts/travis-doc-upload.sh
