language: rust

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6

env:
  - LLVM_VERSION=3.5
  - LLVM_VERSION=3.8
rust:
  - stable
  - nightly
os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: linux
      env: LLVM_VERSION=3.5
      rust: stable
      script: cargo build --features static --verbose
    - os: linux
      env: LLVM_VERSION=3.5
      rust: nightly
      script: cargo build --features clippy --verbose
    - os: osx
      rust: stable
      env: LLVM_VERSION=devtools

notifications:
  webhooks: http://build.servo.org:54856/travis

before_install:
  -
    set -e;
    if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      if [ "${LLVM_VERSION}" == "devtools" ]; then
        export LIBCLANG_PATH=/Library/Developer/CommandLineTools/usr/lib;
      else
        brew update >/dev/null;
        brew install llvm3${LLVM_VERSION#3.};
        export LIBCLANG_PATH=`brew --prefix llvm3${LLVM_VERSION#3.}`/lib/llvm-${LLVM_VERSION}/lib;
      fi;
    else
      if [ "${LLVM_VERSION}" == "3.5" ]; then
        export LLVM_VERSION_TRIPLE=3.5.2;
      else
        export LLVM_VERSION_TRIPLE=3.8.0;
      fi;
      export LLVM=clang+llvm-${LLVM_VERSION_TRIPLE}-x86_64-linux-gnu-ubuntu-14.04;
      wget http://llvm.org/releases/${LLVM_VERSION_TRIPLE}/${LLVM}.tar.xz ;
      mkdir llvm;
      tar -xf ${LLVM}.tar.xz -C llvm --strip-components=1;
      export LIBCLANG_PATH=`pwd`/llvm/lib;
    fi;
  -
    echo $LIBCLANG_PATH;
